parameters:
  name: ''
  vmImage: ''
  continueOnError: false
  go:
    container: golang
    versions: [ 1.13, 1.12 ]
    targets:
      GOARCH: [ amd64 ]

jobs:
  - job: ${{ parameters.name }}
    continueOnError: ${{ parameters.continueOnError }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        ${{ each goVersion in parameters.go.versions }}:
          ${{ each goarch in parameters.go.targets.GOARCH }}:
            ${{ format('go{0}_{1}', goVersion, goarch) }}:
              GOVERSION: ${{ goVersion }}
              GOARCH: ${{ goarch }}
    container:
      image: ${{ parameters.go.container }}:$(GOVERSION)
      env:
        GOARCH: $(GOARCH)
    steps:
      - script: go build -v github.com/jstemmer/go-junit-report
        name: download_tools
        displayName: download tools
      - script: |
          go env
          go test -v ./... 2>&1 | ./go-junit-report > report.xml
        name: go_test
        displayName: go test
      - task: PublishTestResults@2
        inputs:
          testRunner: JUnit
          testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml
          buildPlatform: ${{ parameters.name }}_$(GOVERSION)_$(GOARCH)
